name: 1.18 Auto Build Release Publish

on:
  push:
    branches:
      - 'exp-1.18'
    paths:
      - 'version.gradle'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_PASS: ${{ secrets.MAVEN_PASS }}
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
          
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run the Gradle package task
      uses: gradle/gradle-build-action@2.4.2
      with:
        arguments: build publish

    - name: Get file name
      id: var
      run: |
        MESSAGE=$(ls build/libs/* | grep sources.jar -v)
        echo file_path=$MESSAGE >> $GITHUB_OUTPUT

    - name: Upload to CurseForge
      uses: itsmeow/curseforge-upload@v3
      with:
        token: ${{ secrets.CURSEFORGE_TOKEN }}
        project_id: 604054
        game_endpoint: minecraft
        file_path: ${{ steps.var.outputs.file_path }}
        changelog: See recent commits [here](https://github.com/Low-Drag-MC/Multiblocked/commits/${{ github.sha }}). This is only marked as a beta release so CurseForge shows it on the front page.
        changelog_type: markdown
        # 1.12.2, Java 8
        game_versions: "Minecraft 1.18:1.18.2,Java 17,Forge"
        release_type: beta
        relations: ldlib:requiredDependency,geckolib:optionalDependency,jei:optionalDependency,roughly-enough-items:optionalDependency
